Fix TypeError on setProgress
When `removeFaviconTag` actually removes a tag an error is thrown:

    TypeError: Cannot read property 'getAttribute' of undefined

This is because the underlying array (NodeList?) is mutated and the
cached `l` var is not.

Closes #17
Closes #13
Closes #11